---
title: "Data Visualization Practice"
author: "Daphne Virlar-Knight"
date: "1/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales)
```

```{r load-data}

# Data is too large to upload via file loader in github, so that's why we're pulling the data in this way
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv"),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"))
        return(esc)
    }
)

head(esc)

```

```{r annual-escapement}
# Calculate the annual escapement of the salmon species in the dataset. These include: Chinook, Sockeye, Chum, Coho, and Pink.


annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink"))
    # The %in% operator tells R to select only those items in the Species column

```

```{r ggplot-tutorial}
# basic ggplot
ggplot(annual_esc, aes(x = Species, y = escapement)) +
  geom_col()

# Why does the following NOT make the columns blue?
ggplot(annual_esc, aes(x = Species, y = escapement, fill = "blue")) +
  geom_col()
    # The columns don't turn blue because we told R the color is in the /aesthetics/ argument, rather than the /geometry/ argument. Thus, we actually told R to to fill a with a character string that it defaulted to red.

# To actually make the columns blue, put the color option within the geometry argument.
ggplot(annual_esc, aes(x = Species, y = escapement)) +
  geom_col(fill = "blue")

# To color the bars by a specific region, we would put that in the aesthitcs function.
ggplot(annual_esc, aes(x = Species, y = escapement, fill = SASAP.Region)) +
  geom_col()

# Can also use the pipe operator into a ggplot function. This can be helpful, but it can also make things more difficult to debug later on.
annual_esc %>% 
  filter(SASAP.Region == "Kodiak") %>% 
ggplot(aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point()
```

```{r ggplot-basics2}
# Filter for Kodiak annual escapement
kodiak_esc <- annual_esc %>% 
  filter(SASAP.Region == "Kodiak")

# Make the ggplot nicer by using ggtitle(), ylab(), and theme_bw()

ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + 
  geom_line() + 
  geom_point() +
  ylab("Escapement") + 
  ggtitle("Kodiak Salmon Escapement") +
  theme_bw()

# Tinker with arguments within theme
ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + 
  geom_line() + 
  geom_point() +
  ylab("Escapement") + 
  ggtitle("Kodiak Salmon Escapement") +
  theme_bw() +
  theme(legend.position = "bottom", legend.title = element_blank())


# Hot Tip: Can also save the result of a series of theme() calls to an object to use on multiple plots.
my_theme <- theme_bw() +
  theme(legend.position = "bottom", legend.title = element_blank())

ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + 
  geom_line() + 
  geom_point() +
  ylab("Escapement") + 
  ggtitle("Kodiak Salmon Escapement") +
  my_theme

```

```{r ggplot-basics3}
# Introducing the scales package
# In the ggplot code below, the comma function comes from the scales package. This formats the labels of the y-axis (or x-axis if necessary) to have comma-formatted numbers.

ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point() +
    scale_y_continuous(labels = comma) +
    ylab("Escapement") +
    ggtitle("Kodiak Salmon Escapement") +
    my_theme

# Let's save the graph!
ggsave("kodiak_esc.png", width = 3, height = 3, units = "in")
```

```{r ggplot-basics4}
# Facet wrapping

# Create a plot for every region. The tilde in the facet_wrap() function tells R to model each unique value with a variable_name to a facet in the plot.

# Also, allow for a free y-axis. In other words, let each plot have its own y-axis.

ggplot(annual_esc, aes(x = Year, y = escapement, color = Species)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = comma) +
  facet_wrap(~SASAP.Region, scales = "free_y", ncol = 2) +
  ylab("Escapement") +
  my_theme

```

```{r interactive-table}

# Write a data.frame containing unique sampling locations with no missing values using two new functions from dplyr and tidyr: distinct() and drop_na().
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

# Now display the aboce in an interactive table. We can do this by using the datatable() function from the DT package.

datatable(locations)

```

```{r interactive-map}
# Leaflet uses the %>%  operator, not the + operator.

# addTiles() function without argument will add base tiles to your map from OpenStreetMap. 

# addMarkers() will add a marker at each location specified by the latitude and longitude arguments. The tilde symbol in this function is used to model the coordinates to the map.


leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~Location)


# Can also use leaflet to import Web Map Service (WMS) tiles. Let's create a map that uses the General Bathymetric Map of the Oceans (GEBCO) WMS, and uses a circle marker.

leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)

```





