---
title: "Data Cleaning Basics"
author: "Daphne Virlar-Knight"
date: "1/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, warning=FALSE}
suppressMessages(library(dplyr))
library(tidyr)
library(readr)
```

```{r data-read}
catch_original <- read_csv("df35b.302.1.csv")
```

```{r data-clean}
# Selecting columns we want to keep from original dataset 
catch_data <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)

# Alternatively, we could have done the following to achieve the same result.
catch_data <- catch_original %>% 
  select(-All, -notesRegCode)

# Look at data to make sure everything seems in alignment
head(catch_data)
  # Chinkook column data is classified as character data. We'll need to fix that.

# Changing Chinook data from character to numeric.
catch_clean <- catch_data %>% 
  mutate(Chinook = as.numeric(Chinook))
    # A warning about NAs being introduced has appeared.

# Locate the NA value
which(is.na(catch_clean$Chinook))
  # Output tells us the NA value is in row 401

# Index that row
catch_data[401,]
  # As it turns out, the value present is intended to be a 1. Let's fix it.

# Mutate the I found in row 401 within the Chinook column to be a value of 1.
catch_clean <- catch_data %>% 
  mutate(Chinook = if_else(Chinook == "I", 1, as.numeric(Chinook)))
```

```{r data-shape}
# The data are presented in wide format, but we want it into tall format. Let's rearrange. The pivot_longer() function from the tidyr package allows us to do this.
catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year), names_to = "species", values_to = "catch")

# Look at the data
head(catch_long)

# If you wanted to make tall formatted data wide, you would use pivot_wider.
catch_wide <- catch_long %>% 
  pivot_wider(names_from = species, values_from = catch)
```

```{r dplyr-cleaning}
# Can rename columns using the rename function
catch_long <- catch_long %>% 
  rename(catch_thousands = catch)
  #rename(new_column_name = old_column_name)

head(catch_long)

# Add a new column called catch with units of fish, rather than thousands of fish. Then remove the catch_thousands column.
catch_long <- catch_long %>% 
  mutate(catch = catch_thousands * 1000) %>% 
  select(-catch_thousands)

head(catch_long)
```

```{r data-analysis}
# The combination of the group_by() and summarise() functions employs the "Split-Apply-Combine" strategy used most commonly in data manipulation.
mean_region <- catch_long %>% 
  group_by(Region) %>% 
  summarise(catch_mean = mean(catch))

head(mean_region)

# Another great use of the group_by() and summarise() functions is to count the number of rows in each group. To do that, we use the n() function within the dplyr package.
n_region <- catch_long %>% 
  group_by(Region) %>% 
  summarise(n = n())

head(n_region)

# Alternatively, this can also be achieved with the count() function in the dplyr package.
count(catch_long, Region)
  # Hint: You can't use the data.frame$column.name syntax with count(). Not sure why though.

# Filter rows for only SSE region.
SSE_catch <- catch_long %>% 
  filter(Region == "SSE")

head(SSE_catch)

# Now let's play with the arrange() function.
# Arrange is useful when wanting to calculate the cumulative sum, where row order matters, and when wanting to displace a table in a sorted order.
mean_region <- catch_long %>% 
  group_by(Region) %>% 
  summarise(mean_catch = mean(catch)) %>% 
  arrange(mean_catch)
    # Can also change order from ascending to descending order by doing:
    # arrange(desc(mean_catch))

head(mean_region)

```

```{r data-joins}
# Read in data table that has regions information, and select info we want.
region_defs <- read_csv("df35b.303.1.csv") %>% 
  select(code, mgmtArea)

head(region_defs)

# Join the catch_long data frame with the region_defs data frame, by telling R that the "Region" column in catch_long is identical to the "code" column in the region_defs data frame
catch_joined <- left_join(catch_long, region_defs, by = c("Region" = "code"))


# This could also be accomplished by renaming the columns in the region_defs dataframe, and performing a left join that way.
region_defs <- region_defs %>% 
  rename(Region = code, Region_Name = mgmtArea)

catch_joined <- left_join(catch_long, region_defs, by = c("Region"))

head(catch_joined)
```

```{r data-parsing}
# Learning to use the separate() and unite() functions. Can split a single column into many, or vice versa; typically done by a single character like a space or em-dash.

sites_df <- data.frame(site = c("HAW-101",
                                "HAW-103",
                                "OAH-320",
                                "OAH-219",
                                "MAI-039"))

sites_df <- sites_df %>% 
  separate(site, c("island", "site number"), "-")

head(sites_df)

# Split the following data frame into City and State Code
cities_df <- data.frame(city = c("Juneau AK", 
                                 "Sitka AK", 
                                 "Anchorage AK"))

cities_sep_df <- cities_df %>% 
  separate(city, c("city", "state"), " ")

head(cities_sep_df)

# Explore the unite function
dates_df <- data.frame(year = c("1930",
                                "1930",
                                "1930"),
                       month = c("12",
                                "12",
                                "12"),
                       day = c("14",
                               "15",
                               "16"))

dates_df <- dates_df %>% 
  unite(date, year, month, day, sep = "-")

head(dates_df)

# Use unite to put cities_df back together
cities_unite_df <- cities_sep_df %>% 
  unite(city, city, state, sep = " ")

head(cities_unite_df)
```

```{r}
# Let's put it all together. If we were to run this from scratch, it would look like this:
catch_original <- read_csv("df35b.302.1.csv")
region_defs <- read_csv("df35b.303.1.csv") %>% 
  select(code, mgmtArea)

mean_region <- catch_original %>% 
  select(-All, -notesRegCode) %>% 
  mutate(Chinook = ifelse(Chinook == "I", 1, Chinook)) %>% 
  mutate(Chinook = as.numeric(Chinook)) %>% 
  pivot_longer(-c(Region, Year), names_to = "species", values_to = "catch") %>% 
  mutate(catch = catch*1000) %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch)) %>% 
  left_join(region_defs, by = c("Region" = "code"))

head(mean_region) 
```

