---
title: "Writing Functions & Packages"
author: "Daphne Virlar-Knight"
date: "1/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r intro-functions}
# Create a function that calculates celsies temperature outputs from fahrenheit temperature inputs. 

# Create test values
airtemps <- c(212, 30.3, 78, 32)

# Create the function
fahr_to_celsius <- function(fahr) {
  celsius <- (fahr-32) * 5/9
  return(celsius)
}

fahr_to_celsius(212)
fahr_to_celsius(30.3)

# Rather than checking by hand, we can also run the original vector of information through the function.

fahr_to_celsius(airtemps)


# Create a function to do the reverse.
cels_temp <- fahr_to_celsius(airtemps)

celsius_to_fahr <- function(cels) {
  fahr_temp <- cels*9/5 + 32
  return(fahr_temp)
}


fahr_temp_values <- celsius_to_fahr(cels_temp)


# Check that the function worked
cels_temp == fahr_temp_values
airtemps == fahr_temp_values

```

```{r medium-functions}
# Create a function to convert a list of fahrenheit temps to celsies and kelvin, and then return the a list of the values in F, C, and K

convert_temps <- function(fahr) {
  celsius <- (fahr-32) * 5/9
  kelvin <- celsius + 273.15
  return(list(fahr=fahr, celsius=celsius, kelvin=kelvin))
}

temps_df <- data.frame(convert_temps(seq(-100, 100, 10)))
datatable(temps_df)


```

```{r hard-functions}
# Create a custom ggplot theme
custom_theme <- function(base_size = 9) {
    ggplot2::theme(
      axis.ticks       = ggplot2::element_blank(),
      text             = ggplot2::element_text(family = 'Helvetica', color = 'gray30', size = base_size),
      plot.title       = ggplot2::element_text(size = ggplot2::rel(1.25), hjust = 0.5, face = 'bold'),
      panel.background = ggplot2::element_blank(),
      legend.position  = 'right',
      panel.border     = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_line(colour = 'grey90', size = .25),
      legend.key       = ggplot2::element_rect(colour = NA, fill = NA),
      axis.line        = ggplot2::element_blank()
      )
}

ggplot(temps_df, mapping=aes(x=fahr, y=celsius, color=kelvin)) +
  geom_point() +
  custom_theme(10)

# But we can go further. One can wrap the entire call to ggplot in a function, enabling one to create many plots of the same type with a consistent structure. For example, we can create a scatterplot function that takes a data frame as input, along with a point_size for the points on the plot, and a font_size for the text. 

scatterplot <- function(df, point_size = 2, font_size = 9) {
  ggplot(df, mapping=aes(x=fahr, y=celsius, color=kelvin)) +
    geom_point(size = point_size) +
    custom_theme(font_size)
}

# Let’s set the point size to 3 and font to 16 to make the plot more legible.
scatterplot(temps_df, point_size=3, font_size = 16)

```

